### ISSUE TITLE
Need help with transfer not received 

### ISSUE THREAD

**Issue by jarysanchezz** [chatch/stellarexplorer#341]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by yuttanaGithub** [comment]
i Member Gate.io i make  XLM Coin Withdrawal 8314.271973

Since Date: 2021-11-01 Time 01:11:46 Serial Num : 16629621

To Address Bitkub

GBS2RTBGEWBT7DJOH7CTA4PDVLIPONCPCIILJPPESWSHDIV4NFZJHRP3 1094254860

TXID: cd2893d0995702bdff1c5de7a158a73c29a9acdff74bf299001c3f76156432df

Status: Completed blocked like 30 minutes.

I want blockchain to confirm

But now, date: 2021-11-01 time 16:15:50 has not been completed and confirmed.

https://stellarchain.io/tx/cd2893d0995702bdff1c5de7a158a73c29a9acdff74bf299001c3f76156432df

Can you help me? I‘ve been waiting for a long time.

**Comment by pollee22** [comment]
> 
I don't receive GBS2RTBGEWBT7DJOH7CTA4PDVLIPONCPCIILJPPESWSHIV4NFZJHRP3
![16520168464896154541972365546675](https://user-images.githubusercontent.com/105158671/167298689-a8d2a82c-1bba-44bf-b0a7-0b0a0d91ac4e.jpg)
