### ISSUE TITLE
Link directly to alternative Horizon's (and Soroban RPC servers)

### ISSUE THREAD

**Issue by leighmcculloch** [chatch/stellarexplorer#360]
## Issue Description

Steexp.com is one of the few explorers that supports being pointed at any Horizon or network. It would be very handy to be able to link to steexp.com with a custom network specific in the URL, so that it is possible to link directly to an account, or transaction, or just the home page already setup for that custom network.

**Comment by GHesericsu** [comment]
any progress on this? trying to build a dapp and this feature is very important to users. Thanks.

**Comment by chatch** [comment]
This is now working.

Example: render ledgers list using the testnet servers:
https://steexp.com/ledgers?horizonAddress=https://horizon-testnet.stellar.org&sorobanRPCAddress=https://soroban-testnet.stellar.org

For local backends you'll need to run your own instance (see https://github.com/chatch/stellarexplorer#exploring-private--local-development-networks) due to server side rendering. 

Example: http://publicnet.local:3000/ledgers?horizonAddress=http://localhost:8000&sorobanRPCAddress=http://localhost:8000/soroban/rpc
