### ISSUE TITLE
Federated address links broken

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#506]
## Issue Description

Navigating to a federated address link like https://steexp.com/account/stellar*fed.network fails with:

```
TypeError: T.a is undefined
    value Account.js:455
    value Account.js:435
```

Are we out of sync with the js sdk or something?

**Comment by jp-ryuji** [comment]
Is it something to do with `.well-known/stellar.toml`, which is missing on https://steexp.com?

---

The following seems to be working on my env:
http://publicnet.local:3000/account/stellar*fed.network
https://steexp.com/account/stellar*fed.network

Searching `stellar*fed.network` on http://publicnet.local:3000/ brings me to http://publicnet.local:3000/account/stellar*fed.network .
It's an expected behavior, isn't it?

But `jed*stellar.org` doesn't work.
I got the following error on http://publicnet.local:3000/ :

```
stellar.toml does not contain FEDERATION_SERVER field
```

I confirmed the `isFederatedAddress` function returns true against the both addresses.
So I'm not sure why `stellar*fed.network` works, but `jed*stellar.org` doesn't.

Anyways, it seems to be something to do with `stellar-sdk/lib/stellar_toml_resolver.js`.
But `"stellar-sdk": "10.4.1"`, which we're using, is the latest stable version.

I read the following article and it seems it expects `.well-known/stellar.toml` file.
https://developers.stellar.org/docs/encyclopedia/federation#supporting-federation 

But we don't have `.well-known/stellar.toml`, do we?
Is this the cause?

---

## How other sites work regarding `.well-known/stellar.toml` 

### stellar.expert

https://stellar.expert/.well-known/stellar.toml 
→ not found.

### scopuly.com

https://scopuly.com/.well-known/stellar.toml 
→ It exists.

https://api.scopuly.com/federation?q=jed*stellar.org&type=name
https://api.scopuly.com/federation?q=stellar*fed.network&type=name
→ No record found, but it's working.

**Comment by chatch** [comment]
@jp-ryuji looks like jed no longer resolves: https://stellar.expert/explorer/public/search?term=jed*stellar.org

so it could just be the handling of addresses that don't exist or can't be resolved for some reason?

stellar.toml is only hosted on sites that are anchors. so that's why we don't host it.

but those addresses above do:
- https://stellar.org/.well-known/stellar.toml
- http://fed.network/.well-known/stellar.toml

so must be something in the handling of a federated address lookup when he address does not exist on that server ...

**Comment by chatch** [comment]
here's a description of how federated addreses are resolved: https://developers.stellar.org/docs/encyclopedia/federation#supporting-federation

so you can queries against the FEDERATION_SERVERs to see the response they give and then check the handling we have against that. should be able to see what's going on hopefully.

**Comment by jp-ryuji** [comment]
- https://fed.network/.well-known/stellar.toml has a `FEDERATION_SERVER` section.
- https://stellar.org/.well-known/stellar.toml doesn't have one.

So I'm not sure where I can query `*stellar.org` against.

---

## fed.network

```
$ curl https://fed.network/.well-known/stellar.toml
FEDERATION_SERVER="https://fed.network/federation"

$ curl "https://fed.network/federation?q=stellar*fed.network&type=name"
{"stellar_address":"stellar*fed.network","account_id":"GBMREKAQVMTTNF7HACO5YGM2XZUPGSUSBJZIZ26TAQILKA5HNO32VS4D"}%

$ curl "https://fed.network/federation?q=jed*stellar.org&type=name"
{"detail":"different domain"}%
```

## stellar.org

```
$ curl -I "https://stellar.org/federation?q=jed*stellar.org&type=name"
HTTP/2 404
```

**Comment by chatch** [comment]
@jp-ryuji stellar.org used to support federation but it might be that dropped it - no FEDERATION_SERVER in stellar.toml ...

just looking at `loadAccountByFederatedAddress` where we use stellar-sdk FederationServer to resolve the address.

we don't catch anything there by the looks but stellar.org resolution would result in an error `"stellar.toml does not contain FEDERATION_SERVER field"` ...  so i reckon if you try catch exceptions in that block and look for that error message then we can handle it properly.  and properly would be just the account not found page an 404.
