### ISSUE TITLE
Uncaught Error: network public does not yet have soroban support

### ISSUE THREAD

**Issue by lorenzobersano** [chatch/stellarexplorer#514]
## Issue Description

As of now steexp.com breaks because of the error: network public does not yet have soroban support.
Looks like a problem linked to the stellar lib.

Can this be fixed? As of now we can't use it with our private net.

Thanks!

**Comment by chatch** [comment]
thanks for reporting this @lorenzobersano, apologies just saw this now but this was fixed a couple of days ago: https://github.com/chatch/stellarexplorer/commit/ac97447ada7111fa64fccd25f4c009a7135ec09b

please give it another try. check it pulls a new a copy of the webapp to cache otherwise it'll still occur.
